version: '3.9'

services:
  todo-app:
    container_name: todo-app
    build: 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/root/docs
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD = ${DB_PASSWORD}
    networks:
      - todo-backend

  postgres:
    container_name: todo-db
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - DB_PASSWORD = ${DB_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - todo-backend

networks:
  todo-backend:
    driver: bridge

volumes:
  pg-data:
  