http:
  host: todo-app
  port: 8080
  shutdownTimeout: 5s
  readTimeout: 5s
  writeTimeout: 5s

db:
  maxOpenConns: 5
  maxIdleConns: 5
  connMaxIdleTime: 5m
  connMaxLifetime: 5m

auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 720h

project:
  name: todo-service
  level: debug