http:
  host: 127.0.0.1
  port: 8080
  shutdownTimeout: 5s
  readTimeout: 5s
  writeTimeout: 5s

db:
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  name: "postgres"
  sslmode: "disable"
  maxOpenConns: 5
  maxIdleConns: 5
  connMaxIdleTime: 5m
  connMaxLifetime: 5m
